export const ENVIRONMENT_FACTS = [
  "Anthropogenic climate change has increased vapor pressure deficit, contributing to more severe wildfire behavior in forest ecosystems.",
  "Wildfires release significant quantities of carbon dioxide (CO₂) and black carbon, influencing atmospheric radiative forcing.",
  "Fire suppression policies can lead to fuel accumulation, increasing the intensity of subsequent wildfires.",
  "Pyrolysis during wildfires breaks down organic matter into volatile compounds and char, altering soil chemistry.",
  "Post-wildfire hydrophobic soil layers can reduce water infiltration and increase surface runoff.",
  "Volcanic eruptions emit sulfur dioxide (SO₂), which can form sulfate aerosols that reflect solar radiation and cool the atmosphere.",
  "Ash deposition from volcanoes can alter soil pH and enhance nutrient availability, particularly phosphorus and potassium.",
  "Volcanic carbon emissions are significantly lower than anthropogenic emissions but still contribute to the global carbon cycle.",
  "Subglacial volcanic activity can accelerate ice melt by transferring geothermal heat to overlying ice sheets.",
  "Iceberg calving is influenced by ocean temperature, salinity, and mechanical stress at glacier termini.",
  "Freshwater input from melting icebergs can disrupt thermohaline circulation by altering ocean salinity gradients.",
  "Albedo reduction due to melting ice increases solar absorption, amplifying polar warming through positive feedback.",
  "Tropical rainforests exhibit high net primary productivity due to year-round photosynthetically active radiation.",
  "Deforestation reduces evapotranspiration, which can disrupt regional precipitation cycles.",
  "Rainforest soils are often nutrient-poor, relying on rapid nutrient cycling within biomass.",
  "Mycorrhizal networks in jungle ecosystems facilitate nutrient exchange between plant species.",
  "Riverine systems transport dissolved and particulate organic carbon from terrestrial to marine environments.",
  "Eutrophication in rivers is driven by excess nitrogen and phosphorus inputs, leading to algal blooms.",
  "Hypoxic conditions in aquatic systems can result from microbial decomposition of algal biomass.",
  "Riparian vegetation stabilizes riverbanks and reduces sediment load through root reinforcement.",
  "Hydrological connectivity is essential for maintaining biodiversity in river floodplains.",
  "Glacial meltwater contributes to seasonal river discharge variability in alpine regions.",
  "Permafrost thaw releases methane (CH₄), a potent greenhouse gas, into the atmosphere.",
  "Black carbon deposition on ice surfaces accelerates melting by decreasing surface albedo.",
  "Biodiversity loss can reduce ecosystem resilience and impair ecological function.",
  "Carbon sequestration in forests occurs through biomass accumulation and soil organic carbon storage.",
  "Wildfire regimes are influenced by climatic variables such as temperature, humidity, and wind patterns.",
  "Volcanic eruptions can inject ash into the stratosphere, affecting global aviation safety.",
  "Large igneous province eruptions have historically been linked to mass extinction events.",
  "Ice core samples provide paleoclimate data through trapped gas bubbles and isotopic composition.",
  "Tropical deforestation contributes approximately 10–15% of global greenhouse gas emissions.",
  "River damming alters sediment transport and disrupts aquatic migration patterns.",
  "Sediment trapping behind dams can lead to downstream erosion and delta subsidence.",
  "Jungle canopies regulate microclimates by controlling light penetration and humidity levels.",
  "Evapotranspiration from forests plays a critical role in atmospheric moisture recycling.",
  "Wildfires can convert forests from carbon sinks to carbon sources.",
  "Volcanic ash clouds can travel thousands of kilometers depending on atmospheric circulation.",
  "Melting polar ice contributes to sea level rise through both thermal expansion and mass addition.",
  "Ocean stratification can increase due to freshwater input from melting ice, reducing vertical mixing.",
  "River pollution by heavy metals can bioaccumulate in aquatic food webs.",
  "Deforestation fragments habitats, reducing gene flow among wildlife populations.",
  "Peatland fires release ancient carbon stored over millennia into the atmosphere.",
  "Geothermal activity associated with volcanoes can support unique extremophile ecosystems.",
  "Iceberg drift patterns are influenced by ocean currents, wind, and Coriolis forces.",
  "Floodplain ecosystems rely on periodic inundation for nutrient deposition and regeneration.",
  "Climate-induced shifts in wildfire seasons are extending fire-prone periods globally.",
  "Volcanic aerosols can lead to short-term global dimming effects.",
  "River discharge is a key component of the global hydrological cycle.",
  "Photosynthesis in tropical jungles significantly contributes to global oxygen production.",
  "Anthropogenic land-use change is a primary driver of ecosystem degradation worldwide.",
];
